export const activityStatusMap = {
  draft: '草稿',
  open: '可加入',
  full: '已满',
  closed: '已结束',
  offline: '已下架'
}

export const eventColorTypeMap = {
  course: '课程',
  activity: '已加入活动',
  recommended: '推荐活动',
  conflict: '冲突',
  expired: '已结束'
}

export const defaultRecommendedActivities = [
  {
    title: '人工智能前沿讲座',
    description: '围绕大模型、智能体和可信 AI 的前沿进展进行分享。',
    speaker: '张三教授',
    organizer: '计算机科学与技术学院',
    college: '计算机科学与技术学院',
    category: '讲座',
    campus: '紫金港',
    location: '紫金港校区西区报告厅',
    start_time: '2026-06-06T14:00:00',
    end_time: '2026-06-06T16:00:00',
    hot_score: 87,
    recommend_score: 92,
    status: 'open',
    tags: ['人工智能', '计算机'],
    matched_tags: ['人工智能'],
    reason: '匹配兴趣标签：人工智能'
  },
  {
    title: '数据库系统与智能数据管理研讨会',
    description: '介绍数据库内核、查询优化与智能数据管理在科研场景中的应用。',
    speaker: '李明副教授',
    organizer: '计算机科学与技术学院',
    college: '计算机科学与技术学院',
    category: '研讨会',
    campus: '玉泉',
    location: '玉泉校区曹光彪楼东楼 502',
    start_time: '2026-06-09T15:00:00',
    end_time: '2026-06-09T17:00:00',
    hot_score: 82,
    recommend_score: 88,
    status: 'open',
    tags: ['数据库', '系统'],
    matched_tags: ['数据库'],
    reason: '匹配兴趣标签：数据库'
  },
  {
    title: '机器学习理论与实践学术沙龙',
    description: '围绕监督学习、表示学习和模型评估方法展开小规模学术交流。',
    speaker: '王悦博士',
    organizer: '人工智能研究所',
    college: '计算机科学与技术学院',
    category: '沙龙',
    campus: '紫金港',
    location: '紫金港校区西区创新楼 211',
    start_time: '2026-06-12T19:00:00',
    end_time: '2026-06-12T20:30:00',
    hot_score: 76,
    recommend_score: 84,
    status: 'open',
    tags: ['机器学习', '人工智能'],
    matched_tags: ['人工智能'],
    reason: '根据近期浏览的人工智能活动推荐'
  },
  {
    title: '软件工程项目实践经验分享',
    description: '结合课程项目与真实开发流程，分享需求分析、测试和协作管理经验。',
    speaker: '陈老师',
    organizer: '软件工程课程组',
    college: '软件学院',
    category: '讲座',
    campus: '紫金港',
    location: '紫金港校区东 1A-305',
    start_time: '2026-06-15T13:30:00',
    end_time: '2026-06-15T15:00:00',
    hot_score: 73,
    recommend_score: 81,
    status: 'open',
    tags: ['软件工程', '项目实践'],
    matched_tags: [],
    reason: '同学院与项目实践主题相关'
  },
  {
    title: '可信 AI 与模型安全前沿报告',
    description: '讨论大模型安全、隐私保护、鲁棒性评估与可信人工智能治理。',
    speaker: '赵宁研究员',
    organizer: '人工智能交叉中心',
    college: '计算机科学与技术学院',
    category: '报告',
    campus: '西溪',
    location: '西溪校区教学主楼 120',
    start_time: '2026-06-18T14:00:00',
    end_time: '2026-06-18T16:00:00',
    hot_score: 91,
    recommend_score: 90,
    status: 'open',
    tags: ['人工智能', '安全'],
    matched_tags: ['人工智能'],
    reason: '匹配兴趣标签：人工智能'
  },
  {
    title: '计算机系统结构青年学者论坛',
    description: '聚焦体系结构、操作系统和高性能计算方向的最新研究进展。',
    speaker: '多位青年学者',
    organizer: '计算机系统研究所',
    college: '计算机科学与技术学院',
    category: '论坛',
    campus: '玉泉',
    location: '玉泉校区邵科馆 117',
    start_time: '2026-06-20T09:30:00',
    end_time: '2026-06-20T11:30:00',
    hot_score: 79,
    recommend_score: 83,
    status: 'open',
    tags: ['系统', '计算机'],
    matched_tags: [],
    reason: '最近关注过计算机学院活动'
  },
  {
    title: '自然语言处理与大模型应用分享',
    description: '介绍大模型在问答、信息抽取和智能推荐系统中的应用实践。',
    speaker: '周嘉博士',
    organizer: '数据智能实验室',
    college: '计算机科学与技术学院',
    category: '讲座',
    campus: '紫金港',
    location: '紫金港校区西区报告厅 B',
    start_time: '2026-06-23T18:30:00',
    end_time: '2026-06-23T20:00:00',
    hot_score: 86,
    recommend_score: 89,
    status: 'open',
    tags: ['人工智能', '自然语言处理'],
    matched_tags: ['人工智能'],
    reason: '匹配兴趣标签：人工智能'
  },
  {
    title: '科研论文写作与学术表达工作坊',
    description: '面向本科生和研究生，讲解论文结构、摘要写作和学术汇报技巧。',
    speaker: '刘老师',
    organizer: '本科生科研训练计划',
    college: '信息技术中心',
    category: '工作坊',
    campus: '紫金港',
    location: '紫金港校区图书馆学术报告厅',
    start_time: '2026-06-26T15:30:00',
    end_time: '2026-06-26T17:00:00',
    hot_score: 68,
    recommend_score: 76,
    status: 'open',
    tags: ['科研训练', '学术写作'],
    matched_tags: [],
    reason: '适合补充学术能力训练'
  }
]
